### ISSUE TITLE
Warning for withdrawn papers

### ISSUE THREAD

**Issue by S1M0N38** [dsdanielpark/arxiv2text#2]
When trying to extract text with

```
text = arxiv_to_text("https://arxiv.org/pdf/1802.09703.pdf")
```

the following error arose

```
PDFSyntaxError: No /Root object! - Is this really a PDF?
```

This is caused by the fact that [1802.09703](https://arxiv.org/abs/1802.09703) was withdrawn, hence the PDF is no longer available. Maybe this error message could be improved by suggesting the user navigate to the paper URL and check if the paper is available. I think it's better to separate the error for "PDF not available" from the error "PDF cannot be parsed."

**Comment by dsdanielpark** [comment]
Thank you. I've made the modifications reflecting your feedback. 

I'm delighted to know someone installed the package.

While I can implement features such as comment and image extraction, extraction of LaTeX syntax, and summarization via LLM, I haven't been able to proceed due to time constraints. I'll make sure to find time soon to implement the package more comprehensively.

Thank you.
